version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-dev}
      args:
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE:-.env.local}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # Added recommended settings for production
    restart: unless-stopped
    # Add healthcheck using node
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Add resource limits
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    # Add logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Add network configuration
    networks:
      - app-network
    # Add develop section for compose watch
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/
        - action: rebuild
          path: package.json

networks:
  app-network:
    driver: bridge
